# Generated by Django 3.1.7 on 2021-03-21 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bagsapp', '0002_auto_20210321_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ProductQuantity Entity's ID")),
                ('quantity', models.PositiveIntegerField(default=0, null=True, verbose_name='Quantity Of Product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagsapp.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagsapp.product')),
            ],
        ),
    ]
