# Generated by Django 3.1.7 on 2021-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsapp', '0004_auto_20210321_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bag_h',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Height Of The Bag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bag_w',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Width Of The Bag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bag_weight',
            field=models.PositiveIntegerField(null=True, verbose_name='Weight Of The Bag'),
        ),
    ]
