# Generated by Django 3.1.7 on 2021-03-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsapp', '0005_auto_20210321_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bag_h',
            new_name='bag_height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bag_w',
            new_name='bag_width',
        ),
    ]
