# Generated by Django 3.1.7 on 2021-03-21 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsapp', '0006_auto_20210321_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='added_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='modified_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='added_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='added_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='added_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productquantity',
            name='modified_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
