# Generated by Django 3.1.7 on 2021-03-29 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bagsapp', '0007_auto_20210321_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='added_date_time',
            new_name='created_date_time',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='added_date_time',
            new_name='created_date_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='added_date_time',
            new_name='created_date_time',
        ),
        migrations.RenameField(
            model_name='productquantity',
            old_name='added_date_time',
            new_name='created_date_time',
        ),
        migrations.AlterField(
            model_name='client',
            name='identifier',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Client's ID"),
        ),
    ]
